/// <auto-generated />
using System;
using ImageDotNet.PixelFormats;

namespace ImageDotNet
{
    public enum PixelFormat
    {
        Rgb24,
        Rgba32,
    }

    public static class PixelFormatExtensions
    {
        public static Type ToPixelType(this PixelFormat format)
        {
            switch (format)
            {
                case PixelFormat.Rgb24: return typeof(Rgb24);
                case PixelFormat.Rgba32: return typeof(Rgba32);
            }

            throw new ImageDotNetException($"Unknown {nameof(PixelFormat)}.");
        }
    }
}
