/// <auto-generated />
using Xunit;

namespace ImageDotNet.Tests
{
    public partial class ImageTests
    {
        [Fact]
        public void Is_Bgr24_Bgr24() =>
            Assert.True(new Image<Bgr24>(1, 1, new Bgr24[1]).Is<Bgr24>());

        [Fact]
        public void Is_Bgr24_Bgra32() =>
            Assert.False(new Image<Bgr24>(1, 1, new Bgr24[1]).Is<Bgra32>());

        [Fact]
        public void Is_Bgr24_Rgb24() =>
            Assert.False(new Image<Bgr24>(1, 1, new Bgr24[1]).Is<Rgb24>());

        [Fact]
        public void Is_Bgr24_Rgba32() =>
            Assert.False(new Image<Bgr24>(1, 1, new Bgr24[1]).Is<Rgba32>());

        [Fact]
        public void Is_Bgra32_Bgr24() =>
            Assert.False(new Image<Bgra32>(1, 1, new Bgra32[1]).Is<Bgr24>());

        [Fact]
        public void Is_Bgra32_Bgra32() =>
            Assert.True(new Image<Bgra32>(1, 1, new Bgra32[1]).Is<Bgra32>());

        [Fact]
        public void Is_Bgra32_Rgb24() =>
            Assert.False(new Image<Bgra32>(1, 1, new Bgra32[1]).Is<Rgb24>());

        [Fact]
        public void Is_Bgra32_Rgba32() =>
            Assert.False(new Image<Bgra32>(1, 1, new Bgra32[1]).Is<Rgba32>());

        [Fact]
        public void Is_Rgb24_Bgr24() =>
            Assert.False(new Image<Rgb24>(1, 1, new Rgb24[1]).Is<Bgr24>());

        [Fact]
        public void Is_Rgb24_Bgra32() =>
            Assert.False(new Image<Rgb24>(1, 1, new Rgb24[1]).Is<Bgra32>());

        [Fact]
        public void Is_Rgb24_Rgb24() =>
            Assert.True(new Image<Rgb24>(1, 1, new Rgb24[1]).Is<Rgb24>());

        [Fact]
        public void Is_Rgb24_Rgba32() =>
            Assert.False(new Image<Rgb24>(1, 1, new Rgb24[1]).Is<Rgba32>());

        [Fact]
        public void Is_Rgba32_Bgr24() =>
            Assert.False(new Image<Rgba32>(1, 1, new Rgba32[1]).Is<Bgr24>());

        [Fact]
        public void Is_Rgba32_Bgra32() =>
            Assert.False(new Image<Rgba32>(1, 1, new Rgba32[1]).Is<Bgra32>());

        [Fact]
        public void Is_Rgba32_Rgb24() =>
            Assert.False(new Image<Rgba32>(1, 1, new Rgba32[1]).Is<Rgb24>());

        [Fact]
        public void Is_Rgba32_Rgba32() =>
            Assert.True(new Image<Rgba32>(1, 1, new Rgba32[1]).Is<Rgba32>());
    }
}