/// <auto-generated />
using System;

namespace ImageDotNet.Tests
{
    public static partial class TestData
    {
        public static class Bgr24Images
        {
            public static readonly Bgr24[] Image1x1 = new Bgr24[]
            {
                new Bgr24(1, 2, 3),
            };

            public static readonly Bgr24[] Image2x2 = new Bgr24[]
            {
                new Bgr24(1, 2, 3),new Bgr24(4, 5, 6),
                new Bgr24(7, 8, 9),new Bgr24(10, 11, 12),
            };

            public static readonly Bgr24[] Image3x3 = new Bgr24[]
            {
                new Bgr24(1, 2, 3),new Bgr24(4, 5, 6),new Bgr24(7, 8, 9),
                new Bgr24(10, 11, 12),new Bgr24(13, 14, 15),new Bgr24(16, 17, 18),
                new Bgr24(19, 20, 21),new Bgr24(22, 23, 24),new Bgr24(25, 26, 27),
            };

            public static readonly Bgr24[] Image4x4 = new Bgr24[]
            {
                new Bgr24(1, 2, 3),new Bgr24(4, 5, 6),new Bgr24(7, 8, 9),new Bgr24(10, 11, 12),
                new Bgr24(13, 14, 15),new Bgr24(16, 17, 18),new Bgr24(19, 20, 21),new Bgr24(22, 23, 24),
                new Bgr24(25, 26, 27),new Bgr24(28, 29, 30),new Bgr24(31, 32, 33),new Bgr24(34, 35, 36),
                new Bgr24(37, 38, 39),new Bgr24(40, 41, 42),new Bgr24(43, 44, 45),new Bgr24(46, 47, 48),
            };

            public static readonly Bgr24[] Image5x5 = new Bgr24[]
            {
                new Bgr24(1, 2, 3),new Bgr24(4, 5, 6),new Bgr24(7, 8, 9),new Bgr24(10, 11, 12),new Bgr24(13, 14, 15),
                new Bgr24(16, 17, 18),new Bgr24(19, 20, 21),new Bgr24(22, 23, 24),new Bgr24(25, 26, 27),new Bgr24(28, 29, 30),
                new Bgr24(31, 32, 33),new Bgr24(34, 35, 36),new Bgr24(37, 38, 39),new Bgr24(40, 41, 42),new Bgr24(43, 44, 45),
                new Bgr24(46, 47, 48),new Bgr24(49, 50, 51),new Bgr24(52, 53, 54),new Bgr24(55, 56, 57),new Bgr24(58, 59, 60),
                new Bgr24(61, 62, 63),new Bgr24(64, 65, 66),new Bgr24(67, 68, 69),new Bgr24(70, 71, 72),new Bgr24(73, 74, 75),
            };

        }

        public static class Bgra32Images
        {
            public static readonly Bgra32[] Image1x1 = new Bgra32[]
            {
                new Bgra32(1, 2, 3, 4),
            };

            public static readonly Bgra32[] Image2x2 = new Bgra32[]
            {
                new Bgra32(1, 2, 3, 4),new Bgra32(5, 6, 7, 8),
                new Bgra32(9, 10, 11, 12),new Bgra32(13, 14, 15, 16),
            };

            public static readonly Bgra32[] Image3x3 = new Bgra32[]
            {
                new Bgra32(1, 2, 3, 4),new Bgra32(5, 6, 7, 8),new Bgra32(9, 10, 11, 12),
                new Bgra32(13, 14, 15, 16),new Bgra32(17, 18, 19, 20),new Bgra32(21, 22, 23, 24),
                new Bgra32(25, 26, 27, 28),new Bgra32(29, 30, 31, 32),new Bgra32(33, 34, 35, 36),
            };

            public static readonly Bgra32[] Image4x4 = new Bgra32[]
            {
                new Bgra32(1, 2, 3, 4),new Bgra32(5, 6, 7, 8),new Bgra32(9, 10, 11, 12),new Bgra32(13, 14, 15, 16),
                new Bgra32(17, 18, 19, 20),new Bgra32(21, 22, 23, 24),new Bgra32(25, 26, 27, 28),new Bgra32(29, 30, 31, 32),
                new Bgra32(33, 34, 35, 36),new Bgra32(37, 38, 39, 40),new Bgra32(41, 42, 43, 44),new Bgra32(45, 46, 47, 48),
                new Bgra32(49, 50, 51, 52),new Bgra32(53, 54, 55, 56),new Bgra32(57, 58, 59, 60),new Bgra32(61, 62, 63, 64),
            };

            public static readonly Bgra32[] Image5x5 = new Bgra32[]
            {
                new Bgra32(1, 2, 3, 4),new Bgra32(5, 6, 7, 8),new Bgra32(9, 10, 11, 12),new Bgra32(13, 14, 15, 16),new Bgra32(17, 18, 19, 20),
                new Bgra32(21, 22, 23, 24),new Bgra32(25, 26, 27, 28),new Bgra32(29, 30, 31, 32),new Bgra32(33, 34, 35, 36),new Bgra32(37, 38, 39, 40),
                new Bgra32(41, 42, 43, 44),new Bgra32(45, 46, 47, 48),new Bgra32(49, 50, 51, 52),new Bgra32(53, 54, 55, 56),new Bgra32(57, 58, 59, 60),
                new Bgra32(61, 62, 63, 64),new Bgra32(65, 66, 67, 68),new Bgra32(69, 70, 71, 72),new Bgra32(73, 74, 75, 76),new Bgra32(77, 78, 79, 80),
                new Bgra32(81, 82, 83, 84),new Bgra32(85, 86, 87, 88),new Bgra32(89, 90, 91, 92),new Bgra32(93, 94, 95, 96),new Bgra32(97, 98, 99, 100),
            };

        }

        public static class Rgb24Images
        {
            public static readonly Rgb24[] Image1x1 = new Rgb24[]
            {
                new Rgb24(1, 2, 3),
            };

            public static readonly Rgb24[] Image2x2 = new Rgb24[]
            {
                new Rgb24(1, 2, 3),new Rgb24(4, 5, 6),
                new Rgb24(7, 8, 9),new Rgb24(10, 11, 12),
            };

            public static readonly Rgb24[] Image3x3 = new Rgb24[]
            {
                new Rgb24(1, 2, 3),new Rgb24(4, 5, 6),new Rgb24(7, 8, 9),
                new Rgb24(10, 11, 12),new Rgb24(13, 14, 15),new Rgb24(16, 17, 18),
                new Rgb24(19, 20, 21),new Rgb24(22, 23, 24),new Rgb24(25, 26, 27),
            };

            public static readonly Rgb24[] Image4x4 = new Rgb24[]
            {
                new Rgb24(1, 2, 3),new Rgb24(4, 5, 6),new Rgb24(7, 8, 9),new Rgb24(10, 11, 12),
                new Rgb24(13, 14, 15),new Rgb24(16, 17, 18),new Rgb24(19, 20, 21),new Rgb24(22, 23, 24),
                new Rgb24(25, 26, 27),new Rgb24(28, 29, 30),new Rgb24(31, 32, 33),new Rgb24(34, 35, 36),
                new Rgb24(37, 38, 39),new Rgb24(40, 41, 42),new Rgb24(43, 44, 45),new Rgb24(46, 47, 48),
            };

            public static readonly Rgb24[] Image5x5 = new Rgb24[]
            {
                new Rgb24(1, 2, 3),new Rgb24(4, 5, 6),new Rgb24(7, 8, 9),new Rgb24(10, 11, 12),new Rgb24(13, 14, 15),
                new Rgb24(16, 17, 18),new Rgb24(19, 20, 21),new Rgb24(22, 23, 24),new Rgb24(25, 26, 27),new Rgb24(28, 29, 30),
                new Rgb24(31, 32, 33),new Rgb24(34, 35, 36),new Rgb24(37, 38, 39),new Rgb24(40, 41, 42),new Rgb24(43, 44, 45),
                new Rgb24(46, 47, 48),new Rgb24(49, 50, 51),new Rgb24(52, 53, 54),new Rgb24(55, 56, 57),new Rgb24(58, 59, 60),
                new Rgb24(61, 62, 63),new Rgb24(64, 65, 66),new Rgb24(67, 68, 69),new Rgb24(70, 71, 72),new Rgb24(73, 74, 75),
            };

        }

        public static class Rgba32Images
        {
            public static readonly Rgba32[] Image1x1 = new Rgba32[]
            {
                new Rgba32(1, 2, 3, 4),
            };

            public static readonly Rgba32[] Image2x2 = new Rgba32[]
            {
                new Rgba32(1, 2, 3, 4),new Rgba32(5, 6, 7, 8),
                new Rgba32(9, 10, 11, 12),new Rgba32(13, 14, 15, 16),
            };

            public static readonly Rgba32[] Image3x3 = new Rgba32[]
            {
                new Rgba32(1, 2, 3, 4),new Rgba32(5, 6, 7, 8),new Rgba32(9, 10, 11, 12),
                new Rgba32(13, 14, 15, 16),new Rgba32(17, 18, 19, 20),new Rgba32(21, 22, 23, 24),
                new Rgba32(25, 26, 27, 28),new Rgba32(29, 30, 31, 32),new Rgba32(33, 34, 35, 36),
            };

            public static readonly Rgba32[] Image4x4 = new Rgba32[]
            {
                new Rgba32(1, 2, 3, 4),new Rgba32(5, 6, 7, 8),new Rgba32(9, 10, 11, 12),new Rgba32(13, 14, 15, 16),
                new Rgba32(17, 18, 19, 20),new Rgba32(21, 22, 23, 24),new Rgba32(25, 26, 27, 28),new Rgba32(29, 30, 31, 32),
                new Rgba32(33, 34, 35, 36),new Rgba32(37, 38, 39, 40),new Rgba32(41, 42, 43, 44),new Rgba32(45, 46, 47, 48),
                new Rgba32(49, 50, 51, 52),new Rgba32(53, 54, 55, 56),new Rgba32(57, 58, 59, 60),new Rgba32(61, 62, 63, 64),
            };

            public static readonly Rgba32[] Image5x5 = new Rgba32[]
            {
                new Rgba32(1, 2, 3, 4),new Rgba32(5, 6, 7, 8),new Rgba32(9, 10, 11, 12),new Rgba32(13, 14, 15, 16),new Rgba32(17, 18, 19, 20),
                new Rgba32(21, 22, 23, 24),new Rgba32(25, 26, 27, 28),new Rgba32(29, 30, 31, 32),new Rgba32(33, 34, 35, 36),new Rgba32(37, 38, 39, 40),
                new Rgba32(41, 42, 43, 44),new Rgba32(45, 46, 47, 48),new Rgba32(49, 50, 51, 52),new Rgba32(53, 54, 55, 56),new Rgba32(57, 58, 59, 60),
                new Rgba32(61, 62, 63, 64),new Rgba32(65, 66, 67, 68),new Rgba32(69, 70, 71, 72),new Rgba32(73, 74, 75, 76),new Rgba32(77, 78, 79, 80),
                new Rgba32(81, 82, 83, 84),new Rgba32(85, 86, 87, 88),new Rgba32(89, 90, 91, 92),new Rgba32(93, 94, 95, 96),new Rgba32(97, 98, 99, 100),
            };

        }
    }
}